services:
  hackblog-db:
    image: postgres:15
    container_name: hackblog
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hackblog
    ports:
      - "5434:5432"
    volumes:
      - hackblog_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  hackblog_data:
